# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: EeveeSpotify

on:
  push:
    branches: [ "swift" ]
  pull_request:
    branches: [ "swift" ]

jobs:
  build:
    name: Build EeveeSpotify
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Theos
        run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/roothide/theos/master/bin/install-theos)"

      - name: Setup environment
        run: echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: create theos spm config
        run: make spm
        
      - name: Build EeveeSpotify
        run: swift build
